name: pms_package
description: Nawah PMS module.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core_package:
    path: ../core_package

  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^28.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter