name: eco_system
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_package:
    path: packages/core_package
  ats_package:
    path: packages/ats_package
  strategy_package:
    path: packages/strategy_package
  pms_package:
    path: packages/pms_package

  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^10.0.0
  pin_code_text_field: ^1.8.0
  scroll_to_index: ^3.0.1
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0+3
  app_settings: ^6.1.1
  share_plus:
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.1
  flutter_native_splash: ^2.4.4
  flutter_animate: ^4.5.2
#  syncfusion_flutter_charts: ^28.2.6
  flutter_debouncer: ^2.0.0
  open_file: ^3.5.10
  modal_bottom_sheet: ^3.0.0-pre
#  liquid_glass_renderer: ^0.1.1-dev.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  injectable_generator:
  flutter_lints:

flutter_gen:
  output: packages/core_package/lib/core/core/
  line_length: 80
  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app-icon.png"
  image_path_ios: "assets/app-icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/langs/
    - .env


  fonts:

    - family: en
      fonts:
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Bold.ttf
          weight: 800



    - family: ar
      fonts:
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/IBMPlexSans-Arabic-Bold.ttf
          weight: 800