name: eco_system
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  rxdart: ^0.28.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  pin_code_text_field: ^1.8.0
  scroll_to_index: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  app_settings: ^5.1.1
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  share_plus:
  flutter_image_compress: ^2.4.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  pin_code_fields: ^8.0.1
  flutter_native_splash: ^2.4.4
  flutter_animate: ^4.5.2
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.5+1
  modal_bottom_sheet: ^3.0.0-pre
  easy_localization: ^3.0.2
  readmore: ^3.0.0
  flutter_debouncer: ^2.0.0
  fluttertoast: ^8.2.12
  connectivity_plus: ^5.0.2
  open_file: ^3.5.10





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  injectable_generator:
  flutter_lints:

flutter_gen:
  output: lib/core/
  line_length: 80
  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app-icon.png"
  image_path_ios: "assets/app-icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/langs/
    - .env


  fonts:

    - family: en
      fonts:
        - asset: assets/fonts/en/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/en/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/en/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Light.ttf
          weight: 600
        - asset: assets/fonts/en/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/en/Roboto-Black.ttf
          weight: 800



    - family: ar
      fonts:
        - asset: assets/fonts/ar/Montserrat-Arabic-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/Montserrat-Arabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Montserrat-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Montserrat-Arabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Montserrat-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/ar/Montserrat-Arabic-ExtraBold.ttf
          weight: 800