name: eco_system
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  rxdart: ^0.28.0
  flutter_bloc: ^9.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  pin_code_text_field: ^1.8.0
  scroll_to_index: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  app_settings: ^5.1.1
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  share_plus:
  flutter_image_compress: ^2.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app_icon.png"
  image_path_ios: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/
    - assets/langs/

  fonts:
    - family: en
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: text
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: italic
      fonts:
        - asset: assets/fonts/Raleway-Italic.ttf
    - family: ar
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

