name: strategy_package
description: Nawah Strategy module.
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_package:
    path: ../core_package

  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^28.2.6
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0