name: pms_system
description: Nawah PMS module.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_system:
    path: ../core_system

  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^28.2.6
  url_launcher: ^6.2.1
  intl: ^0.20.2
  html: ^0.15.6


dev_dependencies:
  flutter_test:
    sdk: flutter