name: ats_package
description: Nawah ATS module.
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_package:
    path: ../core_package

dev_dependencies:
  flutter_test:
    sdk: flutter
