name: core_package
description: Shared core utilities and components for eco_system.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ats_package:
    path: ../ats_package
  dio: ^5.8.0+1
  rxdart: ^0.28.0
  flutter_bloc: ^9.0.0
  path_provider: ^2.1.5
  easy_localization: ^3.0.2
  intl: ^0.18.1
#  intl: ^0.20.2
  fluttertoast: ^8.2.12
  connectivity_plus: ^5.0.2
  readmore: ^3.0.0
  shimmer: ^3.0.0
  permission_handler: ^12.0.0+1
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  flutter_local_notifications: ^19.2.1
  image_picker: ^1.1.2
  modal_bottom_sheet: ^3.0.0-pre
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  pin_code_fields: ^8.0.1
  path: ^1.9.0
