default_platform(:android)

platform :android do
  desc "Distribute existing CI-built APK"
  lane :distribute_ci do |options|
    test_email = options[:test_email]

    # Build the APK
    sh(
      "flutter", "build", "apk",
      "--release",
      "--no-shrink",
      "--dart-define=ACTIVE_SYSTEMS=#{ENV['ACTIVE_SYSTEMS']}"
    )


    firebase_args = {
        app: "1:419893562273:android:5d15901a1b38730eb659e0",
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        release_notes: "🚀 Automated CI release from GitHub Actions",
        groups: "nawah-team",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
      }

    # Add testers only if email is provided
      firebase_args[:testers] = test_email unless test_email.to_s.strip.empty?

    # Upload to Firebase App Distribution
      firebase_app_distribution(**firebase_args)
  end
end
