name: Flutter CI

on:
  push:
    branches: [ats]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Run Flutter Static Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze || true

      - name: Run build_runner
        run: |
          if grep -q "build_runner" pubspec.yaml || grep -q "flutter_gen_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi

      - name: Format check
        run: dart format --set-exit-if-changed .
